### PR TITLE
Attempt to fix ql

### PR DESCRIPTION
**Pull request by MasonProtter**
This change seems to fix the example https://github.com/JuliaLinearAlgebra/InfiniteLinearAlgebra.jl/issues/153, but it'd be good if there were also tests we could put in to check.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Great, thanks for that! I probably changed the interface at some point. It would be great if you could a test.

Btw  I forgot that I implemented ∞-QL for such matrices. It probably only works for operators that are asymptotically block Toeplitz, which may not include your original example (it does include bi-infinite discrete Schrödinger operators).

It was very experimental code that hasn't really been used so I'm not sure I'd recommend using it, but if it's something you'd like to explore collaboratively I'd be happy to help.  Doing inverse iteration via `\` might be better as it uses QR instead of QL.

**Comment by MasonProtter** [comment]
> It would be great if you could a test.

Yeah, I just wasn't sure what or how to properly test it.

**Comment by dlfivefifty** [comment]
In the first instance you can just do a test that makes sure It doesn't error. Eg something like `ql(A-x*I).L[1,1] isa Float64`

**Comment by dlfivefifty** [comment]
Looks fine, thanks for that!

Let me know if you want to use this more seriously. The philosophy is very much similar to the discussion on Discourse, that is you do the ∞-dimensional tail exactly, but here we construct matrix factorisations rather than inverses. I'd expect it to be more numerically stable; its essentially the difference between QL algorithm and inverse iteration.

**Comment by MasonProtter** [comment]
Thanks! I think for now, for my puposes, the brute force approach with a truncated matrix is working fine, but I may revisit this soon.

**Comment by MasonProtter** [comment]
@dlfivefifty do you mind merging this? I have merge rights (through JuliaLinearAlgebra) but it feels a little rude for me to do it since I'm not normally active in this repo.

**Comment by dlfivefifty** [comment]
Apologies! I think tests were still running last time I looked

**Comment by MasonProtter** [comment]
Not a problem :)

**Pull request merged**
