### PR TITLE
Fix tests (hopefully)

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
@DanielVandH I think this has hit a bug in the UL code?

**Comment by dlfivefifty** [comment]
oh wait.... the failure is actually in infqr

**Comment by dlfivefifty** [comment]
Hmm... there's a bug in banded matrix broadcasting that is only triggered on MacOS on CI that's breaking a lot of tests.... not sure how to debug it.

**Comment by DanielVandH** [comment]
Weird. I don't believe my code touched any of that. The only relevant recent change would be https://github.com/JuliaArrays/LazyArrays.jl/commit/052a0f6cd85911951b3ec6a6b6030420926d70f6 I think? But nothing there looks like it would ever cause some OS-dependent issue. The manifests between each OS are the same too so that's weird.

**Comment by DanielVandH** [comment]
I've had some array access issues like this before with DelaunayTriangulation.jl with CI bugs that are completely non-existent locally. It took a lot of print debugging and care to get the environment correctly setup to somehow identify the cause (and now the tests just include thousands of random tests everywhere which is a bit annoying)... if it continues to be a problem I can try and look into it if necessary.

**Pull request merged**
